runtime: nodejs20

env_variables:
  SUPABASE_URL: "https://yyayfhfgowguqzvpnghp.supabase.co"
  SUPABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5YXlmaGZnb3dndXF6dnBuZ2hwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNDAwNjYsImV4cCI6MjA3MTYxNjA2Nn0.LmEfxJbEQh0lRCthTiIdJlZbojHG6VORWz9B76zEb-s"